#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

export CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:-3}"
export RUN_NAME="${RUN_NAME:-tfnc_v2_uniform_xpool_8f_expand15_balanced_gpu3}"
export EXP_NAME="${EXP_NAME:-$RUN_NAME}"
export SAVE_PREFIX="${SAVE_PREFIX:-/data/znh/outputs/$RUN_NAME/}"
export TRAIN_ENTRYPOINT="${TRAIN_ENTRYPOINT:-train_lemonfm_uniform_pool.py}"

export TRAINING_METHOD="${TRAINING_METHOD:-tfnc_v2}"
export SELECTION_POOLING="${SELECTION_POOLING:-xpool}"
export TRAIN_WINDOW_EXPAND_RATIO="${TRAIN_WINDOW_EXPAND_RATIO:-1.5}"
export LEVEL_BATCH_SIZES="${LEVEL_BATCH_SIZES:-fine:120,mid:62,coarse:38}"
export ANCHOR_SAME_VIDEO_TRIPLETS="${ANCHOR_SAME_VIDEO_TRIPLETS:-false}"

export TFNC_V2_XPOOL_LOSS_WEIGHT="${TFNC_V2_XPOOL_LOSS_WEIGHT:-1.0}"
export TFNC_V2_OUTSIDE_DENOMINATOR_WEIGHT="${TFNC_V2_OUTSIDE_DENOMINATOR_WEIGHT:-1.0}"

export PER_GPU_BATCH_SIZE="${PER_GPU_BATCH_SIZE:-220}"
export NUM_WORKERS="${NUM_WORKERS:-4}"
export VIDEO_READER_THREADS="${VIDEO_READER_THREADS:-1}"
export VIDEO_READER_CACHE_SIZE="${VIDEO_READER_CACHE_SIZE:-4}"
export DATALOADER_IN_ORDER="${DATALOADER_IN_ORDER:-false}"
export DATALOADER_PREFETCH_FACTOR="${DATALOADER_PREFETCH_FACTOR:-2}"
export DECODE_CPU_THREAD_LIMIT="${DECODE_CPU_THREAD_LIMIT:-1}"

export EPOCHS="${EPOCHS:-50}"

bash run_train_tfnc_swanlab.sh
