PROJECT_ROOT="${PROJECT_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)}"
DATA_ROOT="${DATA_ROOT:-/data/nfs_data/CLIP}"
EXP_NAME="${EXP_NAME:-surglavi_lora_single3090}"

CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:-0}"
IFS=',' read -r -a CUDA_DEVICE_LIST <<< "$CUDA_VISIBLE_DEVICES"
GPU_COUNT="${#CUDA_DEVICE_LIST[@]}"
NPROC="${NPROC:-$GPU_COUNT}"
TORCH_DISTRIBUTED_DEBUG="${TORCH_DISTRIBUTED_DEBUG:-DETAIL}"
TORCH_SHOW_CPP_STACKTRACES="${TORCH_SHOW_CPP_STACKTRACES:-1}"
SWANLAB_EXPERIMENT_NAME="${SWANLAB_EXPERIMENT_NAME:-$EXP_NAME}"
TB_LOGDIR="${TB_LOGDIR:-runs/${EXP_NAME}}"
PYTHONPATH="${PYTHONPATH:-$PROJECT_ROOT}"

EPOCHS="${EPOCHS:-50}"
LEARNING_RATE="${LEARNING_RATE:-5e-5}"
WEIGHT_DECAY="${WEIGHT_DECAY:-0.02}"
ADAM_BETA1="${ADAM_BETA1:-0.9}"
ADAM_BETA2="${ADAM_BETA2:-0.999}"
PER_GPU_BATCH_SIZE="${PER_GPU_BATCH_SIZE:-2}"
TARGET_GLOBAL_BATCH_SIZE="${TARGET_GLOBAL_BATCH_SIZE:-128}"
ACCUM_STEPS="${ACCUM_STEPS:-$(( TARGET_GLOBAL_BATCH_SIZE / (PER_GPU_BATCH_SIZE * NPROC) ))}"
NUM_WORKERS="${NUM_WORKERS:-8}"
IMAGE_SIZE="${IMAGE_SIZE:-224}"
MAX_LENGTH="${MAX_LENGTH:-256}"
NUM_FRAMES="${NUM_FRAMES:-8}"
SEED="${SEED:-42}"
FINETUNE_MODE="${FINETUNE_MODE:-lora}"
LORA_RANK="${LORA_RANK:-8}"
LORA_ALPHA="${LORA_ALPHA:-16}"
LORA_DROPOUT="${LORA_DROPOUT:-0.05}"
LORA_TARGETS="${LORA_TARGETS:-text_encoder.encoder.layer.,vision_encoder.model.blocks.}"
GRADIENT_CHECKPOINTING="${GRADIENT_CHECKPOINTING:-1}"

TOKENIZER_NAME="${TOKENIZER_NAME:-bert-base-uncased}"
SURGCLIP_MODEL_NAME="${SURGCLIP_MODEL_NAME:-SurgCLIP-B}"
VIDEO_ROOT_FOLDER="${VIDEO_ROOT_FOLDER:-${DATA_ROOT}/downloaded_video_224_test}"
ASSUME_RESIZED_VIDEO="${ASSUME_RESIZED_VIDEO:-1}"
MAIN_CSV_PATH="${MAIN_CSV_PATH:-${DATA_ROOT}/surglavi_level_csv/all_video.csv}"
ANNOTATIONS_ROOT="${ANNOTATIONS_ROOT:-${DATA_ROOT}/surglavi_level_csv}"
ANNOTATION_LEVELS="${ANNOTATION_LEVELS:-coarse,mid,fine}"
LEVEL_MIX="${LEVEL_MIX:-concat}"
SAMPLE_MODE="${SAMPLE_MODE:-center}"

SAVE_ROOT="${SAVE_ROOT:-${DATA_ROOT}/surglavi_checkpoint}"
SAVE_DIR="${SAVE_DIR:-${SAVE_ROOT}/${EXP_NAME}}"
SAVE_EVERY="${SAVE_EVERY:-5}"
SAVE_NAME="${SAVE_NAME:-final.pt}"
RESUME_FROM_CHECKPOINT="${RESUME_FROM_CHECKPOINT:-}"

if [[ "$NPROC" -ne "$GPU_COUNT" ]]; then
  echo "NPROC ($NPROC) must match the number of GPUs in CUDA_VISIBLE_DEVICES ($GPU_COUNT)." >&2
  exit 1
fi

if (( PER_GPU_BATCH_SIZE <= 0 )); then
  echo "PER_GPU_BATCH_SIZE must be positive." >&2
  exit 1
fi

if (( ACCUM_STEPS <= 0 )); then
  echo "ACCUM_STEPS must be positive. Current value: $ACCUM_STEPS" >&2
  exit 1
fi

mkdir -p "$SAVE_DIR" "$TB_LOGDIR"
cd "$PROJECT_ROOT"

echo "CUDA_VISIBLE_DEVICES=$CUDA_VISIBLE_DEVICES"
echo "NPROC=$NPROC"
echo "PER_GPU_BATCH_SIZE=$PER_GPU_BATCH_SIZE"
echo "ACCUM_STEPS=$ACCUM_STEPS"
echo "effective_batch_size=$(( PER_GPU_BATCH_SIZE * ACCUM_STEPS * NPROC ))"
echo "FINETUNE_MODE=$FINETUNE_MODE"
echo "GRADIENT_CHECKPOINTING=$GRADIENT_CHECKPOINTING"

CUDA_VISIBLE_DEVICES="$CUDA_VISIBLE_DEVICES" \
TORCH_DISTRIBUTED_DEBUG="$TORCH_DISTRIBUTED_DEBUG" \
TORCH_SHOW_CPP_STACKTRACES="$TORCH_SHOW_CPP_STACKTRACES" \
SWANLAB_EXPERIMENT_NAME="$SWANLAB_EXPERIMENT_NAME" \
TB_LOGDIR="$TB_LOGDIR" \
PYTHONPATH="$PYTHONPATH" \
torchrun --standalone --nproc_per_node="$NPROC" train_surglavi_ddp.py \
  --epochs "$EPOCHS" \
  --learning_rate "$LEARNING_RATE" \
  --weight_decay "$WEIGHT_DECAY" \
  --adam_beta1 "$ADAM_BETA1" \
  --adam_beta2 "$ADAM_BETA2" \
  --per_gpu_batch_size "$PER_GPU_BATCH_SIZE" \
  --accum_steps "$ACCUM_STEPS" \
  --num_workers "$NUM_WORKERS" \
  --image_size "$IMAGE_SIZE" \
  --max_length "$MAX_LENGTH" \
  --num_frames "$NUM_FRAMES" \
  --tokenizer_name "$TOKENIZER_NAME" \
  --surgclip_model_name "$SURGCLIP_MODEL_NAME" \
  --video_root_folder "$VIDEO_ROOT_FOLDER" \
  --assume_resized_video "$ASSUME_RESIZED_VIDEO" \
  --main_csv_path "$MAIN_CSV_PATH" \
  --annotations_root "$ANNOTATIONS_ROOT" \
  --annotation_levels "$ANNOTATION_LEVELS" \
  --level_mix "$LEVEL_MIX" \
  --sample_mode "$SAMPLE_MODE" \
  --save_dir "$SAVE_DIR" \
  --save_every "$SAVE_EVERY" \
  --save_name "$SAVE_NAME" \
  --seed "$SEED" \
  --finetune_mode "$FINETUNE_MODE" \
  --lora_rank "$LORA_RANK" \
  --lora_alpha "$LORA_ALPHA" \
  --lora_dropout "$LORA_DROPOUT" \
  --gradient_checkpointing "$GRADIENT_CHECKPOINTING" \
  --lora_targets "$LORA_TARGETS" \
  ${RESUME_FROM_CHECKPOINT:+--resume_from_checkpoint "$RESUME_FROM_CHECKPOINT"}
